### ISSUE TITLE
Implement ChestXray-14

### ISSUE THREAD

**Issue by nclgbd** [nclgbd/ResearchToolKit#2]
# Overview

### [ChestX-ray8: Hospital-scale Chest X-ray Database and Benchmarks on Weakly-Supervised Classification and Localization of Common Thorax Diseases](https://arxiv.org/pdf/1705.02315v5.pdf)
> Wang, X., Peng, Y., Lu, L., Lu, Z., Bagheri, M., & Summers, R. M. (2017). Chestx-ray8: Hospital-scale chest x-ray database and benchmarks on weakly-supervised classification and localization of common thorax diseases. In Proceedings of the IEEE conference on computer vision and pattern recognition (pp. 2097-2106).
*Note, this dataset was later enlarged to incorporate 14 classes instead of 8. The 14 version can be found [here](https://nihcc.app.box.com/v/ChestXray-NIHCC/file/220660789610).*
* Large benchmarking dataset for a variety of different chest-based diseases, and all of which rely on a chest x-ray
* Pneumonia is a subset of this dataset
* Needed so we can see the performance using a variety of datasets

# Subtasks
- [x] Subset data to Pneumonia
- [x] ~~Subset data to only 1 disease~~
    * No longer needed, include any label that has Pneumonia
- [x] Convert from 1 channel to 3

**Comment by nclgbd** [comment]
# Notes from ChestX-ray14 (Wang et al)
![image](https://github.com/nclgbd/ResearchToolKit/assets/38570878/38b69851-c8ac-4741-8c54-5043f76978ec)

![image](https://github.com/nclgbd/ResearchToolKit/assets/38570878/4c6ac2cc-d4d9-40cc-abd1-9f2728194730)

![image](https://github.com/nclgbd/ResearchToolKit/assets/38570878/327d6693-54ea-4520-a257-4fe5288661a8)
![image](https://github.com/nclgbd/ResearchToolKit/assets/38570878/fadea5e8-b6f4-4f35-a5b4-57748ae91fa0)

**Comment by nclgbd** [comment]
- [ ] Find out how many children in this dataset have pneumonia
    * This will allow us to add in some Pneumonia scans from the pediatrics dataset to help with the class imbalance
